<?php
//error reporting. Disable these three lines before deployment.
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

/*this file is the main connector and handles data cleaning and issues of login */

// load .env if present
require_once __DIR__ . '/env.php';

// database config from env with sensible defaults
$host = getenv('DB_HOST') ?: '127.0.0.1';
$user = getenv('DB_USER') ?: 'rentakaya_dev';
$usrpassword = getenv('DB_PASSWORD') ?: 'devpass';
$database = getenv('DB_NAME') ?: 'kayadb';

// optional for sending SMS via sms.textsms.co.ke API (from env)
$sms_apiKey = getenv('SMS_API_KEY') ?: 'YourAPIKey';
$sms_partnerID = getenv('SMS_PARTNER_ID') ?: 'YourPartinerID';
$sms_shortcode = getenv('SMS_SHORTCODE') ?: 'TextSMS';


  /* DATABASE CONNECTIONS AS DEFINED IN VARIOUS PAGES*/
        //VARIABLES
       global $connection, $mysqli, $conn;

        //INITIALIZING VARIABLES FOR IMPERATIVE AND OOP

    //for OOP uses - attempt to create mysqli object but catch exceptions
    try {
      $mysqli = new mysqli($host, $user, $usrpassword, $database);
    } catch (mysqli_sql_exception $e) {
      // If mysqli OOP constructor fails (e.g., access denied), set to null
      $mysqli = null;
    }
    //for imperative - wrap in try/catch to avoid uncaught exceptions
    try {
      $conn = mysqli_connect($host, $user, $usrpassword, $database);
    } catch (mysqli_sql_exception $e) {
      $conn = null;
    }

    // $connection was the original connector in OOP, same as $conn
    try {
      $connection = mysqli_connect($host, $user, $usrpassword, $database);
    } catch (mysqli_sql_exception $e) {
      $connection = null;
    }


      if(!$connection){
        //if connection fails, do not abort; expose error details for diagnostics
        $connection = null;
        $db_error_message = 'Failed to connect via mysqli procedural';
      } else {
        $db_error_message = null;
      }

      try{
        //for PDO (use correct DSN 'host')
          $db = new PDO('mysql:host='.$host.';dbname='.$database.';charset=utf8',$user,$usrpassword);
          $pdo_error_message = null;
      }
      catch(Exception $e){
          // PDO failed - keep null and store message for diagnostics
          $db = null;
          $pdo_error_message = $e->getMessage();
      }

      /*DATABASE CONNECTION COMPLETE*/


      /*********************************************************
                  other basic methods
      **********************************************************/

      //function for sending an SMS. I used TextSMS.co.ke API
      function sendSMS($number, $message) 
  {

              // Data to be sent in the POST request
              $postData = [
                      "apikey" => $sms_apiKey,
                      "partnerID" => $sms_partnerID, 
                      "message" => $message,
                      "shortcode" => $sms_shortcode,
                      "mobile" => $number,
                  ];

              // Initialize cURL for making the POST request
              $ch = curl_init("https://sms.textsms.co.ke/api/services/sendsms/");
              curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
              curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($postData));
              curl_setopt($ch, CURLOPT_HTTPHEADER, [
                              'Content-Type: application/json' // Set content type to JSON
              ]);

                          // Execute the request and handle potential errors. use these variables for later tests
              $response = curl_exec($ch); //store response
              $error = curl_error($ch); //store error

              curl_close($ch);  
  }

        //this function is designed to counter sql injection and format the inputs
      function uncrack($data){
        $data=trim($data);
        $data= htmlspecialchars($data);
        $data=stripcslashes($data);

        //replace quotes and forward slashes for SQL
        $data=str_replace('"', '\\"', $data);
        $data=str_replace("'", "\\'", $data);

        return $data;
      };

       //format usernames
    function is_username($data){
      $data=uncrack($data);
      $data=strtolower($data);
      $data=ucwords($data);
      return $data;
    }

     //format emails
    function is_email($data){
      $data=uncrack($data);
      $data=strtolower($data);
      return $data;
    }

    //not so important but it is critical too for temporary autogenerated passwords.
    function random_password() {
        $alphabet = 'abcdefghijklmnopqrstuvwxyz.ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890@%&';
        $pass = array(); //remember to declare $pass as an array
        $alphaLength = strlen($alphabet) - 1; //put the length -1 in cache
        for ($i = 0; $i < 8; $i++) {
            $n = rand(0, $alphaLength);
            $pass[] = $alphabet[$n];
        }
        return implode($pass); //turn the array into a string
    }

   
    function is_logged_in_permanent(){
      if (isset($_COOKIE["name"]) && isset($_COOKIE["tsc"]) && isset($_COOKIE["type"])) {
        //set global variables for logged users and return true
        global $uname, $tsc, $type, $funame;

        $uname=$_COOKIE["name"];
        $tsc=$_COOKIE["tsc"];
        $type=$_COOKIE["type"];
        $funame=substr($uname, 0,strpos($uname," "));//first name

        return true;
      }
      else
      { 
        return false;
      }
    }

     function is_logged_in_temporary(){

      if (isset($_SESSION['email'])) {
        //set global variables for logged users and return true
        global $username;

        $email=$_SESSION["email"];
        $username=substr($email, 0,strpos($email,"@"));//user name

        return true;
      }
      else
      { 
        return false;
      }
    }

    /**
     * Return connection status and error messages for diagnostics.
     * @return array keys: mysqli_oop, mysqli_proc, pdo, errors
     */
    function get_db_status(){
      global $mysqli, $conn, $connection, $db, $db_error_message, $pdo_error_message;
      $status = [
        'mysqli_oop' => isset($mysqli) && $mysqli instanceof mysqli && !$mysqli->connect_errno,
        'mysqli_proc' => isset($conn) && $conn !== null && @mysqli_ping($conn),
        'connection' => isset($connection) && $connection !== null && @mysqli_ping($connection),
        'pdo' => isset($db) && $db instanceof PDO,
        'errors' => []
      ];

      if (!empty($db_error_message)) $status['errors'][] = $db_error_message;
      if (!empty($pdo_error_message)) $status['errors'][] = $pdo_error_message;
      if (isset($mysqli) && $mysqli instanceof mysqli && $mysqli->connect_errno) $status['errors'][] = 'mysqli_oop: '.$mysqli->connect_error;
      if (isset($conn) && $conn && !@mysqli_ping($conn)) $status['errors'][] = 'mysqli_proc: cannot ping server';

      return $status;
    }

    /**
     * Check whether a given column exists in a table (safe helper).
     * @param mysqli|null $mysqli
     * @param string $table
     * @param string $column
     * @return bool
     */
    function has_column($mysqli, $table, $column) {
      if (!$mysqli) return false;
      try {
        $t = $mysqli->real_escape_string($table);
        $c = $mysqli->real_escape_string($column);
        $r = $mysqli->query("SHOW COLUMNS FROM `{$t}` LIKE '{$c}'");
        return $r && $r->num_rows > 0;
      } catch (Exception $e) { return false; }
    }
?>